apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tkmkq2zal-nodejs 
  janus-idp.io/tekton: tkmkq2zal-nodejs
  backstage.io/kubernetes-id: tkmkq2zal-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tkmkq2zal-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml